# Generated by Django 5.2.1 on 2025-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHOP_NAME', models.CharField(default='My shop', help_text='The name of the shop', max_length=100, verbose_name='Name of the shop')),
                ('VERSION_AUTO_UPDATE', models.BooleanField(default=False, help_text='Allows to automatically update the software from official repository (requires internet access)', verbose_name='Automatic updates')),
                ('VERSION_CODE', models.CharField(blank=True, default='', max_length=10, verbose_name='Code of the current version')),
                ('LAN_IP', models.GenericIPAddressField()),
                ('SEC2LOGOUT', models.PositiveSmallIntegerField(default=0, help_text='Seconds after when, the user would need to login again', verbose_name='Seconds to logout')),
                ('VAT', models.FloatField(help_text='Percentage of the cost added as a tax', verbose_name='VAT')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
