# Generated by Django 5.2.1 on 2025-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTPV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='LAN_IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='VAT',
            field=models.FloatField(default=21.0, help_text='Percentage of the cost added as a tax', verbose_name='VAT'),
        ),
    ]
