# Generated by Django 5.2.1 on 2025-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Surname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('cif', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Tax number')),
                ('saves_paper', models.BooleanField(default=False, help_text='Desires to receive the receipts electronically', verbose_name='Electronic receipt')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last name'),
        ),
    ]
