# Generated by Django 5.2.1 on 2025-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAPP', '0002_customer_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cif',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='Tax number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
