# Generated by Django 5.2.1 on 2025-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAPP', '0003_alter_customer_cif_alter_customer_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_reports', 'Can view reports'), ('can_see_historics', 'Can access historic bills'), ('can_edit_stock', 'Can manually modify stock values'), ('can_edit_prices', 'Can manually modify prices'), ('can_add_customer', 'Can create a new customer'), ('can_add_billaccount', 'Can create a new bill'))},
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
