# Generated by Django 5.2.1 on 2025-05-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAPP', '0005_alter_customer_email_alter_user_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
