# Generated by Django 5.2.1 on 2025-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumible',
            name='barcode',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Barcode'),
            preserve_default=False,
        ),
    ]
