# Generated by Django 5.2.1 on 2025-05-13 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0002_consumible_barcode_product_barcode'),
        ('UsersAPP', '0002_customer_alter_user_email_alter_user_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billaccount',
            name='createdBy',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='UsersAPP.customer'),
        ),
    ]
