# Generated by Django 5.2.1 on 2025-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0003_billaccount_createdby_alter_billaccount_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaccount',
            name='paymenttype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'On cash'), (1, 'By credit card')], null=True, verbose_name='Type'),
        ),
    ]
