# Generated by Django 5.2.1 on 2025-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0004_billaccount_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaccount',
            name='paymenttype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On cash'), (1, 'By credit card')], null=True, verbose_name='Type'),
        ),
    ]
