# Generated by Django 5.2.1 on 2025-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0005_alter_billaccount_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaccount',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Closed not Paid'), (2, 'Closed and Paid')], default=0, editable=False, verbose_name='Estado'),
        ),
    ]
