# Generated by Django 5.2.1 on 2025-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0006_alter_billaccount_date_alter_billaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaccount',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='bill_lines', through='ProductsAPP.BillPosition', to='ProductsAPP.product'),
        ),
    ]
