# Generated by Django 5.2.1 on 2025-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0007_alter_billaccount_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
