# Generated by Django 5.2.1 on 2025-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0008_alter_consumible_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
