# Generated by Django 5.2.1 on 2025-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0009_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='stock',
            field=models.FloatField(blank=True, default=0, help_text='Quantity in stock currently', verbose_name='Current stock'),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='stock_min',
            field=models.FloatField(blank=True, default=0, help_text='Quantity in stock that will require a new purchase order', verbose_name='Minimum stock'),
        ),
    ]
