# Generated by Django 5.2.1 on 2025-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0010_alter_consumible_stock_alter_consumible_stock_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaccount',
            name='invoice',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
