# Generated by Django 5.2.1 on 2025-05-14 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0011_billaccount_invoice'),
        ('UsersAPP', '0002_customer_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage over selling price')),
            ],
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='UsersAPP.customer'),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='paymenttype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On cash'), (1, 'By credit card')], null=True, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Closed not Paid'), (2, 'Closed and Paid')], default=0, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='ProductsAPP.productdiscount'),
        ),
    ]
