# Generated by Django 5.2.1 on 2025-05-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0012_productdiscount_alter_billaccount_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_affected', to='ProductsAPP.productdiscount'),
        ),
    ]
