# Generated by Django 5.2.1 on 2025-05-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0013_alter_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billaccount',
            old_name='date',
            new_name='createdOn',
        ),
    ]
