# Generated by Django 5.2.1 on 2025-05-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0014_rename_date_billaccount_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billposition',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_positions', to='ProductsAPP.billaccount'),
        ),
        migrations.AlterField(
            model_name='billposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_positions', to='ProductsAPP.product'),
        ),
    ]
