# Generated by Django 5.2.1 on 2025-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0015_alter_billposition_bill_alter_billposition_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billaccount',
            name='invoice',
        ),
        migrations.AddField(
            model_name='billaccount',
            name='total',
            field=models.FloatField(blank=True, help_text='Total cost of the invoice', null=True, verbose_name='Total cost'),
        ),
        migrations.AddField(
            model_name='billposition',
            name='pvp',
            field=models.FloatField(blank=True, help_text='Precio de venta de una unidad', null=True, verbose_name='Precio de venta'),
        ),
    ]
