# Generated by Django 5.2.1 on 2025-05-20 15:20

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0016_remove_billaccount_invoice_billaccount_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinationposition',
            options={'verbose_name': 'Combination of consumables', 'verbose_name_plural': 'Combinations of consumables'},
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Closed not Paid'), (2, 'Closed and Paid')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='billposition',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='billposition',
            name='pvp',
            field=models.FloatField(blank=True, help_text='Selling price at the moment of the operation', null=True, verbose_name='Selling price'),
        ),
        migrations.AlterField(
            model_name='billposition',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='combinationposition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='ProductsAPP.consumible', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='combinationposition',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_price',
            field=models.FloatField(blank=True, help_text='Override automatic selling price of one unit', null=True, verbose_name='Override selling price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\Users\\mikel.zabaleta\\Github\\TPV\\media'), upload_to='', verbose_name='Image of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='single_ingredient',
            field=models.BooleanField(default=False, verbose_name='Direct from consumable'),
        ),
    ]
