# Generated by Django 5.2.1 on 2025-05-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0017_alter_combinationposition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('pc_value', models.FloatField(help_text='Percentage over product value', verbose_name='Percentage value')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='consumible',
            name='pvp',
        ),
        migrations.AddField(
            model_name='consumible',
            name='price',
            field=models.FloatField(default=10, help_text='Selling price of one unit excluding VAT', verbose_name='Selling price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumible',
            name='cost',
            field=models.FloatField(help_text='Cost of one unit excluding VAT', verbose_name='Unitary cost'),
        ),
        migrations.AddField(
            model_name='consumible',
            name='vat',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL, related_name='consumibles', to='ProductsAPP.vatvalue', verbose_name='Applicable VAT'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ProductsAPP.vatvalue', verbose_name='Applicable VAT'),
        ),
    ]
