# Generated by Django 5.2.1 on 2025-05-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0018_vatvalue_remove_consumible_pvp_consumible_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumibles', to='ProductsAPP.vatvalue', verbose_name='Applicable VAT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ProductsAPP.vatvalue', verbose_name='Applicable VAT'),
        ),
    ]
