# Generated by Django 5.2.1 on 2025-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0019_alter_consumible_vat_alter_product_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='billaccount',
            name='vat_amount',
            field=models.FloatField(blank=True, help_text='Total amount of the VAT', null=True, verbose_name='VAT amount'),
        ),
        migrations.AlterField(
            model_name='billaccount',
            name='total',
            field=models.FloatField(blank=True, help_text='Total cost of the invoice before VAT', null=True, verbose_name='Total amount'),
        ),
    ]
