# Generated by Django 5.2.1 on 2025-05-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0020_billaccount_vat_amount_alter_billaccount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationposition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isUsedIn', to='ProductsAPP.consumible', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumibles', to='ProductsAPP.productfamily', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ProductsAPP.productdiscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ProductsAPP.productfamily'),
        ),
    ]
