# Generated by Django 5.2.1 on 2025-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0022_manufacturer_alter_billaccount_paymenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumible',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='consumible',
            unique_together={('name', 'manufacturer')},
        ),
    ]
