# Generated by Django 5.2.1 on 2025-05-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAPP', '0024_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Units to pay', models.SmallIntegerField()),
                ('Units to take', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='billaccount',
            name='save_amount',
            field=models.FloatField(blank=True, help_text='Total amount saved by discounts/promotions', null=True, verbose_name='Save amount'),
        ),
        migrations.AddField(
            model_name='billposition',
            name='reduce_concept',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billposition',
            name='reduce_subtotal',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ProductsAPP.productpromotion'),
        ),
    ]
